### ISSUE TITLE
Total global hashrate of all workers

### ISSUE THREAD

**Issue by sarog** [suda/dashing-mining-dashboard#1]
Hi, I hope all is well. I have installed your dashboard easily on herokuapp while learning quite a bit I must say. I went ahead and created the separate worker dashboards (`miner01.erb`, `miner02.erb`, etc.) for all my cgminer instances found across several machines. Now, when I visit each separate dashboard individually (`/miner01`, `/miner02`, etc.) I am greeted with the correct hashrate and temperatures for each cgminer instance. This is awesome.

I am interested to know if there is a way to pool all the collected data from the agents into one mega dashboard, say `/global`, and show me the overall total hashrate, accepted & rejected shares, hardware errors and average temperatures (or highest & lowest reported temperatures across the miners). While having individual miners report their statistics is definitely welcomed, I would love to see the overall collective data shown on a single dashboard. A single 20" monitor mounted on my wall showing my aggregate mh/s will make it all the sweeter.

Your time & work in this project is much appreciated.

**Comment by suda** [comment]
Actually this is on my todo list :) It looks a little like this:
- Adding dashboards without the need to commit sources
- Easy switching between dashboards (without manual url changing)
- Dashboard with data aggregated from all workers

Can't really tell when this will be done as currently my time is limited, but hope to implement it soon.

**Comment by ghost** [comment]
Any news if you were able to aggregate the stats? :)

**Comment by suda** [comment]
@computeronix no sorry, project hasn't receive any updates since last year. I invite anyone willing to contribute though.

**Comment by ghost** [comment]
Added to todo list in readme, closing case
