### ISSUE TITLE
Running without heroku

### ISSUE THREAD

**Issue by sooth** [suda/dashing-mining-dashboard#2]
I'm trying to get your software here set up to run on a local Ubuntu server rather than using Heroku.

I've installed Ruby, Rails, dependencies, checked out your code, ran gem bundle/gem bundle install, and all needed tools, tried running "rails server" and the other alternatives, but your software does not seem to use rails.

How is this software launched/used locally?

Looking forward to using this, it looks amazing.

**Comment by suda** [comment]
[Dashing](http://shopify.github.io/dashing/) is using [Sinatra](http://www.sinatrarb.com/). As this is a custom Dashing project, you can launch it using:

```
$ cd dashing-mining-dashboard
$ bundle
$ dashing start
```

Dashboard will be available at [localhost:3030](http://localhost:3030/).

If you want to launch this dashboard as daemon, try one of this scripts: https://gist.github.com/gregology/5313326

**Comment by sooth** [comment]
Thanks! I've got it running both on my heroku instance and locally and I'm having the same problem on both..

I've got the web server running fine, I run the agent on the machine, it creates new data in the history.json file, but I never get any data in either my heroku or local instance, the panels just have their titles and no data. I've tried resubmitting, tweaking IP's, and changing the auth-tokens, but still nothing. Any suggestions?

**Comment by suda** [comment]
I've found that some devices with iOS, don't show any numbers. Does this happen to you on iOS?

Also, this could be silly, but does your URL match with dashboard name (.erb file in dashboards/ directory) i.e. `http://localhost:3030/foo` and `dashboards/foo.erb` ?

**Comment by ghost** [comment]
I have followed these instructions as well and the data is sent over to the dashing server but no values are displayed.  Any ideas?

**Comment by ghost** [comment]
Nevermind, figured it out :)

URL needed to be: http://localhost:3030/   (nothing after it)  Also I had to go into the config.erb and remove "ENV[auth_token]" and replace with 'code' and then use this code on the agent

Also the dashboard needed to be installed in ~/home instead of /opt (due to permissions, although you can get around this with chmod)

**Comment by ghost** [comment]
Updated README to include the required steps to setup your own dashboard server
